apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      role: healthmanager
  template:
    metadata:
      labels:
        role: healthmanager
    spec:
      containers:
      - name: healthmanager
        image: softcomputo/healthmanager:1.4.6
        ports:
        - containerPort: 8080
